{{- if .Values.zipkin.enabled -}}
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "cs.fullname" $ }}-zipkin-deployment
  labels:
    component: zipkin
    app: {{ template "cs.name" . }}
    chart: {{ template "cs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: zipkin
      app: {{ template "cs.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        component: zipkin
        app: {{ template "cs.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: zipkin
          image: "{{ .Values.zipkin.image.repository }}:{{ .Values.zipkin.image.tag }}"
          imagePullPolicy: {{ $.Values.zipkin.image.imagePullPolicy }}
          ports:
            - containerPort: 9411
          resources:
            limits:
              memory: "1G"
              cpu: "0.5"
          livenessProbe:
            tcpSocket:
              port: 9411
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 9411
            failureThreshold: 24
        {{- end }}
