apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    chart: {{ include "mongodb.chart" . }}
    instance: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    role: mongo
