{{range .Values.infrastructure }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "cargo-security.name" $ }}-{{ .name }}-service"
  labels:
    component: {{ .name }}
    app: {{ template "cargo-security.name" $ }}
    chart: {{ template "cargo-security.chart" $ }}
    instance: {{ $.Release.Name }}
    managed-by: {{ $.Release.Service }}
spec:
  type: {{.type}}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
  selector:
    component: {{ .name }}
    instance: {{ $.Release.Name }}

--- 
{{- end }}
    
