replicaCount: 1

infrastructure:
  deviceservice:
    name: device
    replicas: 1
    port: 4100
    type: LoadBalancer
    image:
      repository: cargosecurityregistry.azurecr.io/cs-device-gateway-image
      tag: 0.0.4
      imagePullPolicy: Always

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local



imageCredentials:
  name: acr-auth
  registry: cargosecurityregistry.azurecr.io
  username: cargosecurityregistry
  password: whyVSAsX1RLapaJFkJ7+DRXZCswpBcr=


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
# requests:
#  cpu: 100m
#  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
